### PR TITLE
App Bucket

### PR DESCRIPTION
**Pull request by arun-kumar-codes**

### CODE REVIEW

**Review by karikushi — CHANGES_REQUESTED** [review]
@reactexcel Thanks for submitting the AppBucket component. Please see the comments for some change requests. There's one substantial one about managing the component's state with Redux, and the others are minor.

**Comment by reactexcel** [comment]
Thanks for reviewing, I'll make the requested changes.

**Comment by reactexcel** [comment]
@karikushi I have made the requested changes. Please review once and let me know any other changes that has to be done, if any. Thanks

**Comment by karikushi** [comment]
Thanks for submitting the changes. We don't have any further updates to request.

**Comment by reactexcel** [comment]
Okay. Thank you for your help.

**Pull request closed without merging**
